[project]
name = "llm_chat_mocking_demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.21",
    "langchain-anthropic>=0.3.10",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
]
