# Braincrew ver.250701
# .github/workflows/pr-check.yml
# https://docs.astral.sh/uv/guides/integration/github/

name: "Python PR Check with uv & pytest"
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened]
    branches:
      - dev
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies with uv
        run: |
          if [ -f "uv.lock" ]; then
            uv sync
          else
            echo "uv.lock not found, try running uv install with requirements.txt"
            uv pip sync requirements.txt
          fi
      
      - name: "Run tests with Pytest"
        run: uv run pytest